## Creating a Comment


In [ ]:
#This is a comment
print("Hello, World!")

Hello, World!


In [ ]:
#This is a comment
#written in
#more than just one line
print("Hello, World!")

Hello, World!


In [ ]:
"""
This is a comment
written in
more than just one line
"""
print("Hello, World!")

Hello, World!


## Variables

In [ ]:
x = 5
y = "John"
print(x, type(x))
print(y, type(y))

5 <class 'int'>
John <class 'str'>


In [ ]:
x, y, z = "Orange", "Banana", "Cherry"
print(x)
print(y)
print(z)

Orange
Banana
Cherry


In [ ]:
x = y = z = "Orange"
print(x)
print(y)
print(z)

Orange
Orange
Orange


In [ ]:
x = 5
y = 10
print("z=",(x + y))

z= 15


In [ ]:

x = 5
y = "John"
print(str(x) + y)

5John


In [ ]:
x = "awesome"

def myfunc():
  print("Python is " + x)

myfunc()

Python is awesome


In [ ]:
x = "awesome"

def myfunc():
  x = "fantastic"
  print("Python is " + x)

myfunc()

print("Python is " + x)

Python is fantastic
Python is awesome


In [ ]:
x = "awesome"

def myfunc():
  global x
  x = "fantastic"

myfunc()

print("Python is " + x)

Python is fantastic


## Python Conditions and If statements

Python supports the usual logical conditions from mathematics:

    Equals: a == b
    Not Equals: a != b
    Less than: a < b
    Less than or equal to: a <= b
    Greater than: a > b
    Greater than or equal to: a >= b


In [ ]:
a = 33
b = 200
if b > a:
  print("b is greater than a")

b is greater than a


In [ ]:
a = 33
b = 33
if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")

a and b are equal


In [ ]:
a = 200
b = 33
if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")
else:
  print("a is greater than b")

a is greater than b


In [ ]:
a = 200
b = 33
c = 500
if a > b and c > a:
  print("Both conditions are True")

Both conditions are True


## Loops

In [ ]:
i = 2
while i < 6 and i>1:
  print(i)
  i += 1

2
3
4
5


In [ ]:
i = 0
while i < 6:
  i += 1
  if i == 3:
    pass
  print(i)

1
2
3
4
5
6


In [ ]:
i = 1
while i < 6:
  print(i)
  i += 1
else:
  print("i is no longer less than 6")

1
2
3
4
5
i is no longer less than 6


In [ ]:
fruits = ["apple", "banana", "cherry"]

for x in fruits:
  print(x)

apple
banana
cherry


In [ ]:
fruits = ["apple", "banana", "cherry"]
for x in fruits:
  if x == "banana":
    break
  print(x)

apple


In [ ]:
 fruits = ["apple", "banana", "cherry"]
for x in fruits:
  if x == "banana":
    continue
  print(x)

apple
cherry


In [ ]:
for x in range(0,12,2):
  print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [ ]:
for x in range(6):
  print(x)
else:
  print("Finally finished!")

0
1
2
3
4
5
Finally finished!


In [ ]:
adj = ["red", "big", "tasty"]
fruits = ["apple", "banana", "cherry"]

for x in adj:
  for y in fruits:
    if y=="banana":
        continue
    print(x, y)

red apple
red cherry
big apple
big cherry
tasty apple
tasty cherry


## Functions

In [ ]:
def my_function():
  print("Hello from a function")

my_function()

Hello from a function
Hello from a function


In [ ]:
def my_function(fname, lname):

  print(f"The person name is {fname} {lname}")

my_function("Emil","There")
#my_function("Tobias")
#my_function("Linus")

The person name is Emil There


In [ ]:
def my_function(country = "Norway"):
  print("I am from " + country)

my_function("Sweden")
my_function()


I am from Sweden
I am from Norway


In [ ]:
from types import MappingProxyType

SABITLER = MappingProxyType({"COUNTRY":"Sweeden", "CITY":"Ankara"})
print(SABITLER)

COUNTRY="TURKEY"
print(SABITLER)




{'COUNTRY': 'Sweeden', 'CITY': 'Ankara'}
I am from TURKEY


In [ ]:
def my_function(food):
  for x in food:
    print(x)

fruits = ["apple", "banana", "cherry"]

my_function(fruits)

apple
banana
cherry


In [ ]:
def my_function(x):
  return 5 * x

print(my_function(3))
print(my_function(5))
print(my_function(9))

15
25
45


In [ ]:
def my_function(child3, child2, child1):
  print("The youngest child is " + child3)

#my_function(child1 = "Emil", child2 = "Tobias", child3 = "Linus")
my_function("Emil", "Tobias", "Linus")

The youngest child is Emil


In [ ]:
def my_function(*kids):
  print("The youngest child is " + kids[2]+ str(type(kids)))

my_function("Emil", "Tobias", "Linus")

The youngest child is Linus<class 'tuple'>


## Lambda Function
A lambda function is a small anonymous function.

A lambda function can take any number of arguments, but can only have one expression.

In [ ]:
x = lambda a : a + 10
print(x(5))

15


In [ ]:
x = lambda a, b : a * b
print(x(5, 6))

<function <lambda> at 0x7b786171f740>


In [ ]:
def myfunc(n):
  return lambda a : a * n

mydoubler = myfunc(2)

print(mydoubler(11))

22


In [ ]:
def myfunc(n):
  return lambda a : a * n

mydoubler = myfunc(2)
mytripler = myfunc(3)

print(mydoubler(11))
print(mytripler(11))

22
33


## Class

In [ ]:
class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age

  def myfunc(self):
    print("Hello my name is " + self.name)

p1 = Person("John", 36)
p1.myfunc()

Hello my name is John


In [ ]:
class Student(Person):
  pass
x = Student("Mike", 20)
x.myfunc()

Hello my name is Mike


In [ ]:
class Student(Person):
    def __init__(self, fname, age):
        super().__init__(fname, age)  # Call the parent class constructor
        print(fname)  # This will still print the name

x = Student("Mike", 20)
x.myfunc()

Mike
Hello my name is Mike


In [ ]:
class Student(Person):
  def __init__(self, fname, age):
    Person.__init__(self, fname, age)
x = Student("Mike", 20)
x.myfunc()

Hello my name is Mike


In [ ]:
class Student(Person):
  def __init__(self, fname, age):
    super().__init__(fname, age)

x = Student("Mike", 20)
x.myfunc()

Hello my name is Mike


## Iterators

In [ ]:
mytuple = ("apple", "banana", "cherry")  # A tuple is defined
myit = iter(mytuple)  # Creating an iterator object from the tuple

print(next(myit))  # Fetches the next item in the iterator -> "apple"
print(next(myit))  # Fetches the next item -> "banana"
print(next(myit))  # Fetches the next item -> "cherry"

apple
banana


In [ ]:
mytuple = ("apple", "banana", "cherry")

for x in mytuple:
  print(x)

apple
banana
cherry


## Module

Save this code in a file named mymodule.py

<code>
def greeting(name):
  print("Hello, " + name)
<code>

In [ ]:
import mymodule

mymodule.greeting("Jonathan")

Hello, Jonathan


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## RegEx

In [ ]:
import re

txt = "The rain in Spain"
x = re.search("^The.*ain$", txt)
print(x.string)


The rain in Spain


In [ ]:
import re

str = "The rain in Spain"
x = re.findall("ai", str)
print(x)

['ai', 'ai']


In [ ]:
import re

str = "The rain in Spain"
x = re.search("\s", str)

print("The first white-space character is located in position:", x.start() )

The first white-space character is located in position: 3


In [ ]:
import re

str = "The rain in Spain"
x = re.split("\s", str)
print(x)

['The', 'rain', 'in', 'Spain']


In [ ]:

import re

str = "The rain in Spain"
x = re.sub("\s", "9", str)
print(x)

The9rain9in9Spain


## Try Except

The try block lets you test a block of code for errors. <br/>
The except block lets you handle the error. <br/>
The finally block lets you execute code, regardless of the result of the try- and except blocks.

In [ ]:
try:
  print(xy)
except:
  print("An exception occurred")

An exception occurred


In [ ]:
try:
  print(z)
except NameError:
  print("Variable z is not defined")
except:
  print("Something else went wrong")

Variable x is not defined


In [ ]:
try:
  print("Hello")
except:
  print("Something went wrong")
else:
  print("Nothing went wrong")

Hello
Nothing went wrong


In [ ]:

try:
  print(ty)
except:
  print("Something went wrong")
finally:
  print("The 'try except' is finished")

Something went wrong
The 'try except' is finished


## File

In [ ]:
f = open("demofile.txt", "a")
f.write("Now the file has more content!")
f.close()



In [ ]:
#open and read the file after the appending:
f = open("demofile.txt", "r")
print(f.read())

Now the file has more content!


In [ ]:
import os
os.remove("demofile.txt")

FileNotFoundError: [Errno 2] No such file or directory: 'demofile.txt'

## comparing list and numpy

In [ ]:
import numpy as np

In [ ]:
size=10000
l1=range(size)
l2=range(size)
a1=np.arange(size)
a2=np.arange(size)



In [ ]:
a1

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [ ]:
import sys,time

In [ ]:
lsize= sys.getsizeof(1)*len(l1)
print(lsize)

print(sys.getsizeof(1))

280000
28


In [ ]:
print(a1)

[   0    1    2 ... 9997 9998 9999]


In [ ]:
asize = a1.size*a1.itemsize
print(asize)


80000
8


In [ ]:
t1= time.time()
tlist=[x+y for x,y in zip(l1,l2)]
t2= time.time()
execution_time=t2-t1
print("Execution time :",execution_time )
#print(tlist)


Execution time : 0.005393266677856445


In [ ]:
t1= time.time()
tarray=a1+a2
t2= time.time()
execution_time=t2-t1
print("Execution time :",execution_time )
print(tarray)


Execution time : 0.0005660057067871094
[    0     2     4 ... 19994 19996 19998]


In [ ]:
Z= np.zeros((6,6))
print(Z)
print("")
Z[1:5:3,1::2]=1
print(Z)

Z= np.zeros((6,6))
print("")
Z[::2,1::2]=1
print(Z)


[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0.]]

[[0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0.]]
